### ISSUE TITLE
Adds WhatsApp link

### ISSUE THREAD

**Issue by JesuHrz** [barranquillajs/official-page#18]
**Description**
Add WhatsApp icon in order to be redirected to community whatsApp group

**Acceptance criteria:**
- Redirect to: https://chat.whatsapp.com/Cgkiea91hbpH2kErkjrmxb
- Icons link: https://phosphoricons.com/?q=%22whatsapp%22

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/82fc537c-35a7-4691-be9a-9ed56d027a1f">

**Comment by luisdelaros4** [comment]
He creado un PR que resuelve este issue. Puedes revisarlo en el PR #22.

**Comment by JesuHrz** [comment]
> He creado un PR que resuelve este issue. Puedes revisarlo en el PR #22.

Hola @LuisDelaRos4, este issue fue resuelto en el [PR#30](https://github.com/barranquillajs/official-page/pull/30) - muchas gracias por la contribución durante la Hacktoberfest 2024, asi que te esperamos el proximo año entrante.
