### ISSUE TITLE
Adds Github link

### ISSUE THREAD

**Issue by JesuHrz** [barranquillajs/official-page#19]
**Description**
Add Github icon in order to be redirected to repository of the community

**Acceptance criteria:**
- Redirect to: https://github.com/barranquillajs
- Reuse the Github icon that is used in the codebase

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/4a741adb-81ec-4dbb-94a2-a9d5449ba83a">

**Comment by luisdelaros4** [comment]
He creado un PR que resuelve este issue. Puedes revisarlo en el PR #22.
